### ISSUE TITLE
Git init fails

### ISSUE THREAD

**Issue by typ-ex** [hashicorp/learn-terraform-resource-targeting#1]
![image](https://user-images.githubusercontent.com/19269683/117749123-d46d9080-b1d6-11eb-87d7-92f17833fa7a.png)

My result from running git init after git clone.

Tried on windows 10 machine and WSL 2.  Not sure where it's pulling 3.36 from?

**Comment by im2nguyen** [comment]
Hi @typ-ex , thank you for reporting this!

The configuration uses the [`s3-bucket`](https://registry.terraform.io/modules/terraform-aws-modules/s3-bucket/aws/latest) module which requires an AWS version of greater than `v3.36.0` ([`versions.tf`](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/master/versions.tf)).

However, the configuration previously had the AWS version constraint set to `~> 3.28.0`. As a result, Terraform didn't know which version of AWS to download since it had to greater than `v3.36.0` but still within `v3.28.x`. 

I updated the AWS version constraint in the [`main.tf` file to `~> 3.39.0`](https://github.com/hashicorp/learn-terraform-resource-targeting/commit/c67d991e27d99717a549a3d98c6d763bebdbfd27#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbb) so it fulfills the constraint for the `s3-bucket` module, then ran `terraform init -upgrade` to upgrade the lock file (so future runs pull the same provider versions).

Please let me know if this makes sense and thanks again for reporting this!

**Comment by typ-ex** [comment]
It makes sense once I read the documentation about the pessimistic constraint operator.  It's a new one to me.  

Thank you for resolving the issue @im2nguyen 

Link in the event anybody else runs into this issue

https://www.terraform.io/docs/language/expressions/version-constraints.html
